name: Issue assignment

on:
    issues:
        types: [opened, edited, moved]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: azhiya,courtneyr-dev
                  numOfAssignee: 2
                  allowSelfAssign: false
